//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Festejos
    {
        public int Id { get; set; }
        public string festejo { get; set; }
        public string tipo_festejo { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
    }
}
